import { Project } from '@/types';

export const projects: Project[] = [
  {
    slug: 'digital-birth-death-registration',
    title: 'Digital Birth and Death Registration System',
    description: 'A secure, scalable platform for civil registration, replacing paper processes with digital workflows.',
    longDescription: 'Comprehensive system built for government agencies...',
    technologies: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'Redis'],
    thumbnail: '/projects/digital-registration.jpg',
    screenshots: ['/projects/digital-reg1.jpg', '/projects/digital-reg2.jpg'],
    githubUrl: 'https://github.com/Joseph-Wachira/birth-death-registration',
    liveUrl: '',
    status: 'Completed',
    completionDate: '2024-11',
    category: 'Full-Stack',
    featured: true,
    challenges: ['Legacy data migration', 'Real-time sync across offices'],
    solutions: ['ETL pipelines', 'WebSocket integration'],
    architecture: 'Microservices',
    keyFeatures: ['Role-based access', 'PDF certificates', 'Search & analytics'],
    lessonsLearned: ['Importance of data validation at scale'],
    tags: ['Government', 'Full-Stack', 'Microservices'],
    futureImprovements: ['Blockchain timestamping', 'Mobile offline support'],
  },
  
  {
    slug: 'pomodoro',
    title: 'Pomodoro',
    description: 'A modern, production-ready Pomodoro timer with deep work analytics, glassmorphism UI, sound notifications, and dark/light mode.',
    longDescription: 'A polished productivity app focused on focus sessions, analytics, and a calm user experience.',
    technologies: ['JavaScript', 'React', 'Tailwind CSS', 'Vite'],
    thumbnail: '/projects/pomodoro.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/Joseph-Wachira/pomodoro',
    liveUrl: 'https://pomodorotimer04.netlify.app/',
    status: 'Completed',
    completionDate: '2025',
    category: 'Productivity',
    featured: true,
    challenges: ['Designing a calm focus experience', 'Building reusable timer states'],
    solutions: ['Glassmorphism UI', 'Session analytics and notifications'],
    keyFeatures: ['Pomodoro sessions', 'Deep work analytics', 'Sound notifications', 'Theme switcher'],
    lessonsLearned: ['Small interaction details greatly improve focus tools'],
    tags: ['Productivity', 'Frontend', 'UI/UX'],
    futureImprovements: ['Data persistence', 'Weekly insights'],
  },
  {
    slug: 'weather-dashboard',
    title: 'Weather Dashboard',
    description: 'A beautiful, responsive weather dashboard built with React, Vite, Tailwind CSS, and OpenWeatherMap API.',
    longDescription: 'A responsive weather experience with search history, dynamic visuals, and a 5-day forecast.',
    technologies: ['JavaScript', 'React', 'Tailwind CSS', 'Vite', 'API'],
    thumbnail: '/projects/weather-dashboard.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/Joseph-Wachira/weather-dashboard',
    liveUrl: 'https://weatherdashboard04.netlify.app/',
    status: 'Completed',
    completionDate: '2025',
    category: 'Dashboard',
    featured: true,
    challenges: ['Handling weather API responses gracefully', 'Creating polished responsive layouts'],
    solutions: ['Dynamic UI states', 'Forecast cards and search history'],
    keyFeatures: ['5-day forecast', 'Search history', 'Smooth animations', 'Dynamic backgrounds'],
    lessonsLearned: ['API-driven UIs need strong loading and error handling'],
    tags: ['Weather', 'Frontend', 'API'],
    futureImprovements: ['Geolocation', 'Hourly forecast'],
  },
  {
    slug: 'joseph-wachira',
    title: 'Joseph-Wachira',
    description: 'A GitHub profile repository linked to Joseph Wachira’s public profile and project hub.',
    longDescription: 'A lightweight profile repository that complements the broader portfolio and GitHub presence.',
    technologies: ['GitHub', 'Markdown'],
    thumbnail: '/projects/profile-repo.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/Joseph-Wachira/Joseph-Wachira',
    liveUrl: '',
    status: 'Maintained',
    completionDate: '2025',
    category: 'Profile',
    featured: false,
    challenges: ['Keeping the profile concise and useful'],
    solutions: ['Clear project organization and links'],
    keyFeatures: ['GitHub profile', 'Project showcase', 'Links to repositories'],
    lessonsLearned: ['A strong profile improves discoverability'],
    tags: ['Profile', 'GitHub'],
    futureImprovements: ['More structured project highlights'],
  },
  {
    slug: 'telegram-openai-bot',
    title: 'Telegram OpenAI Bot',
    description: 'A Python-based Telegram bot integrated with OpenAI for conversational interactions.',
    longDescription: 'A bot project that combines Telegram messaging with AI-powered responses.',
    technologies: ['Python', 'Telegram Bot API', 'OpenAI'],
    thumbnail: '/projects/telegram-bot.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/Joseph-Wachira/telegram-openai.bot',
    liveUrl: '',
    status: 'Completed',
    completionDate: '2025',
    category: 'Automation',
    featured: false,
    challenges: ['Reliable bot response handling', 'API integration'],
    solutions: ['Structured command handling', 'Async message processing'],
    keyFeatures: ['Telegram integration', 'AI chat responses', 'Simple deployment'],
    lessonsLearned: ['Bot UX depends heavily on response timing'],
    tags: ['Python', 'Bot', 'AI'],
    futureImprovements: ['Better memory and context'],
  },
  {
    slug: 'movec-store',
    title: 'Movec Store',
    description: 'An e-commerce platform built at Figbloom Digital Group Ltd for Starlink and CCTV products, covering product management, inventory, search/filtering, cart, checkout, and admin/customer workflows.',
    longDescription: 'A full-stack e-commerce system for Starlink internet solutions, CCTV surveillance systems, networking equipment, and smart devices, covering product browsing, order tracking, multiple payment gateways, and an administrative dashboard for managing inventory and orders. Built with a focus on modular architecture, maintainability, and CI/CD-oriented deployment.',
    technologies: ['React', 'TypeScript', 'NestJS', 'PostgreSQL', 'Prisma', 'Tailwind CSS', 'Framer Motion', 'Docker'],
    thumbnail: '/projects/movec-store.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/FigbloomDigitalGroup/movec-store',
    liveUrl: 'https://movecstore.movecconnect.com',
    status: 'Maintained',
    completionDate: '2026',
    category: 'Full-Stack',
    featured: true,
    challenges: ['Integrating multiple payment gateways (M-Pesa, Paystack, PayPal)', 'Building a reliable order tracking flow', 'Designing an admin dashboard for non-technical store operators'],
    solutions: ['Unified payment abstraction layer across providers', 'Order status pipeline with real-time updates', 'Role-based admin dashboard with Cloudinary-backed media management'],
    architecture: 'NestJS REST API with Prisma/PostgreSQL, React SPA frontend, Cloudinary for image hosting',
    keyFeatures: ['Category-based product browsing', 'Shopping cart and wishlist', 'M-Pesa, Paystack, and PayPal checkout', 'Order tracking', 'Admin dashboard', 'Customizable homepage banners'],
    lessonsLearned: ['Payment integrations need robust error handling for real-world reliability', 'Admin tooling is as important as the customer-facing storefront'],
    tags: ['E-Commerce', 'Full-Stack', 'Payments'],
    futureImprovements: ['Inventory analytics', 'Customer reviews and ratings'],
  },
  {
    slug: 'figbloom-property-management-platform',
    title: 'Property Management Platform',
    description: 'A full-stack property management platform built at Figbloom Digital Group Ltd, covering workspaces, properties, units, tenancy operations, billing, and per-user session security.',
    longDescription: 'Internal platform for managing properties, tenancy operations, and billing. Designed backend endpoints and database models for workspace billing, per-user session security, and property defaults, and built the corresponding React frontend pages. Implemented session-based security workflows, including listing/revoking active sessions and OTP-driven verification, and integrated Paystack for payment processing across billing workflows.',
    technologies: ['React', 'NestJS', 'PostgreSQL', 'Prisma', 'REST APIs', 'JWT', 'Paystack'],
    thumbnail: '/projects/property-management.jpg',
    screenshots: [],
    githubUrl: '',
    liveUrl: '',
    status: 'Maintained',
    completionDate: '2026-07',
    category: 'Full-Stack',
    featured: true,
    challenges: ['Modeling multi-tenant workspace billing and property defaults', 'Building secure, revocable per-user session management', 'Integrating Paystack across multiple billing workflows'],
    solutions: ['Modular NestJS services with Prisma-backed data models', 'Session listing/revocation with OTP-driven verification', 'Unified Paystack integration for platform billing'],
    architecture: 'NestJS REST API with Prisma/PostgreSQL, React frontend',
    keyFeatures: ['Workspace billing', 'Per-user session security & revocation', 'OTP verification', 'Property defaults', 'Paystack payment integration'],
    lessonsLearned: ['Session security needs to be revocable, not just authenticated', 'Billing logic is easiest to reason about when modeled close to the workspace/tenancy structure'],
    tags: ['Property Management', 'Full-Stack', 'Security', 'Payments'],
    futureImprovements: ['Expanded billing analytics', 'Additional payment provider support'],
  },
  {
    slug: 'ai-educational-assistant-chatbot',
    title: 'AI Educational Assistant Chatbot',
    description: 'An AI-oriented educational chatbot concept focused on contextual learning support and structured conversational responses.',
    longDescription: 'A personal project exploring how an LLM-backed assistant can support contextual learning, with an application architecture designed for future extensibility toward real-time information retrieval and additional AI capabilities.',
    technologies: ['Python', 'AI/LLM APIs'],
    thumbnail: '/projects/ai-chatbot.jpg',
    screenshots: [],
    githubUrl: '',
    liveUrl: '',
    status: 'Completed',
    completionDate: '2025',
    category: 'AI/Automation',
    featured: false,
    challenges: ['Structuring contextual, curriculum-aware responses', 'Designing for future extensibility'],
    solutions: ['Structured conversational response design', 'Modular architecture for adding retrieval and AI capabilities later'],
    keyFeatures: ['Contextual learning support', 'Structured conversational responses'],
    lessonsLearned: ['Designing for extensibility up front makes it easier to layer in retrieval and new AI capabilities later'],
    tags: ['AI', 'Python', 'Education'],
    futureImprovements: ['Real-time information retrieval', 'Additional AI capabilities'],
  },
  {
    slug: 'joe-car-deals',
    title: 'Joe Car Deals',
    description: 'A car dealership and listings site for browsing available vehicles and viewing detailed car information.',
    longDescription: 'A car dealership site where visitors can browse vehicle listings and view detail pages with specs and images for each car.',
    technologies: ['Next.js', 'TypeScript', 'Tailwind CSS'],
    thumbnail: '/projects/joe-car-deals.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/Joseph-Wachira/joe-car-deals',
    liveUrl: 'https://joe-car-deals-web-zeta.vercel.app',
    status: 'In Progress',
    completionDate: '2026',
    category: 'Full-Stack',
    featured: true,
    challenges: ['Configuring remote image domains for Next.js Image', 'Structuring vehicle listing and detail pages'],
    solutions: ['Next.js Image remote patterns configuration', 'Reusable listing/detail page components'],
    keyFeatures: ['Vehicle listings', 'Car detail pages', 'Responsive design'],
    lessonsLearned: ['Next.js image optimization requires explicit domain configuration for external image sources'],
    tags: ['Automotive', 'Frontend', 'Next.js'],
    futureImprovements: ['Search and filtering', 'Contact/inquiry form'],
  },
  {
    slug: 'pygame-chess',
    title: 'Pygame Chess',
    description: 'A chess game built with Python and Pygame featuring a playable board and classic rules.',
    longDescription: 'An interactive chess project focused on game logic, UI feedback, and a simple arcade-style experience.',
    technologies: ['Python', 'Pygame', 'HTML'],
    thumbnail: '/projects/chess.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/Joseph-Wachira/pygameChess-main-master',
    liveUrl: '',
    status: 'Completed',
    completionDate: '2025',
    category: 'Game',
    featured: false,
    challenges: ['Chess rules implementation', 'Board interaction'],
    solutions: ['Turn-based game logic', 'Clear UI state management'],
    keyFeatures: ['Playable chess board', 'Piece movement', 'Simple UI'],
    lessonsLearned: ['Game logic grows quickly without structured state'],
    tags: ['Game', 'Python'],
    futureImprovements: ['AI opponent', 'Sound effects'],
  },
];