import { Project } from '@/types';

export const projects: Project[] = [
  {
    slug: 'digital-birth-death-registration',
    title: 'Digital Birth and Death Registration System',
    description: 'A secure, scalable platform for civil registration, replacing paper processes with digital workflows.',
    longDescription: 'Comprehensive system built for government agencies...',
    technologies: ['React', 'Node.js', 'PostgreSQL', 'Docker', 'Redis'],
    thumbnail: '/projects/digital-registration.jpg',
    screenshots: ['/projects/digital-reg1.jpg', '/projects/digital-reg2.jpg'],
    githubUrl: 'https://github.com/Joseph-Wachira/birth-death-registration',
    liveUrl: '',
    status: 'Completed',
    completionDate: '2024-11',
    category: 'Full-Stack',
    featured: true,
    challenges: ['Legacy data migration', 'Real-time sync across offices'],
    solutions: ['ETL pipelines', 'WebSocket integration'],
    architecture: 'Microservices',
    keyFeatures: ['Role-based access', 'PDF certificates', 'Search & analytics'],
    lessonsLearned: ['Importance of data validation at scale'],
    tags: ['Government', 'Full-Stack', 'Microservices'],
    futureImprovements: ['Blockchain timestamping', 'Mobile offline support'],
  },
  {
    slug: 'snake-classic',
    title: 'Snake Classic',
    description: 'Modern twist on the classic snake game with leaderboards and power-ups.',
    longDescription: 'Built with React and Canvas API...',
    technologies: ['React', 'TypeScript', 'Canvas', 'Firebase'],
    thumbnail: '/projects/snake.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/Joseph-Wachira/snake-classic',
    liveUrl: '',
    status: 'Completed',
    completionDate: '2024-06',
    category: 'Game',
    featured: true,
    challenges: ['Smooth animations', 'Mobile controls'],
    solutions: ['requestAnimationFrame loop', 'Touch gestures'],
    keyFeatures: ['Power-ups', 'Global leaderboard', 'Responsive design'],
    lessonsLearned: ['Canvas performance optimization'],
    tags: ['Game', 'Frontend'],
    futureImprovements: ['Multiplayer mode'],
  },
  {
    slug: 'pomodoro',
    title: 'Pomodoro',
    description: 'A modern, production-ready Pomodoro timer with deep work analytics, glassmorphism UI, sound notifications, and dark/light mode.',
    longDescription: 'A polished productivity app focused on focus sessions, analytics, and a calm user experience.',
    technologies: ['JavaScript', 'React', 'Tailwind CSS', 'Vite'],
    thumbnail: '/projects/pomodoro.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/Joseph-Wachira/pomodoro',
    liveUrl: 'https://pomodorotimer04.netlify.app/',
    status: 'Completed',
    completionDate: '2025',
    category: 'Productivity',
    featured: true,
    challenges: ['Designing a calm focus experience', 'Building reusable timer states'],
    solutions: ['Glassmorphism UI', 'Session analytics and notifications'],
    keyFeatures: ['Pomodoro sessions', 'Deep work analytics', 'Sound notifications', 'Theme switcher'],
    lessonsLearned: ['Small interaction details greatly improve focus tools'],
    tags: ['Productivity', 'Frontend', 'UI/UX'],
    futureImprovements: ['Data persistence', 'Weekly insights'],
  },
  {
    slug: 'weather-dashboard',
    title: 'Weather Dashboard',
    description: 'A beautiful, responsive weather dashboard built with React, Vite, Tailwind CSS, and OpenWeatherMap API.',
    longDescription: 'A responsive weather experience with search history, dynamic visuals, and a 5-day forecast.',
    technologies: ['JavaScript', 'React', 'Tailwind CSS', 'Vite', 'API'],
    thumbnail: '/projects/weather-dashboard.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/Joseph-Wachira/weather-dashboard',
    liveUrl: 'https://weatherdashboard04.netlify.app/',
    status: 'Completed',
    completionDate: '2025',
    category: 'Dashboard',
    featured: true,
    challenges: ['Handling weather API responses gracefully', 'Creating polished responsive layouts'],
    solutions: ['Dynamic UI states', 'Forecast cards and search history'],
    keyFeatures: ['5-day forecast', 'Search history', 'Smooth animations', 'Dynamic backgrounds'],
    lessonsLearned: ['API-driven UIs need strong loading and error handling'],
    tags: ['Weather', 'Frontend', 'API'],
    futureImprovements: ['Geolocation', 'Hourly forecast'],
  },
  {
    slug: 'joseph-wachira',
    title: 'Joseph-Wachira',
    description: 'A GitHub profile repository linked to Joseph Wachira’s public profile and project hub.',
    longDescription: 'A lightweight profile repository that complements the broader portfolio and GitHub presence.',
    technologies: ['GitHub', 'Markdown'],
    thumbnail: '/projects/profile-repo.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/Joseph-Wachira/Joseph-Wachira',
    liveUrl: '',
    status: 'Maintained',
    completionDate: '2025',
    category: 'Profile',
    featured: false,
    challenges: ['Keeping the profile concise and useful'],
    solutions: ['Clear project organization and links'],
    keyFeatures: ['GitHub profile', 'Project showcase', 'Links to repositories'],
    lessonsLearned: ['A strong profile improves discoverability'],
    tags: ['Profile', 'GitHub'],
    futureImprovements: ['More structured project highlights'],
  },
  {
    slug: 'telegram-openai-bot',
    title: 'Telegram OpenAI Bot',
    description: 'A Python-based Telegram bot integrated with OpenAI for conversational interactions.',
    longDescription: 'A bot project that combines Telegram messaging with AI-powered responses.',
    technologies: ['Python', 'Telegram Bot API', 'OpenAI'],
    thumbnail: '/projects/telegram-bot.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/Joseph-Wachira/telegram-openai.bot',
    liveUrl: '',
    status: 'Completed',
    completionDate: '2025',
    category: 'Automation',
    featured: false,
    challenges: ['Reliable bot response handling', 'API integration'],
    solutions: ['Structured command handling', 'Async message processing'],
    keyFeatures: ['Telegram integration', 'AI chat responses', 'Simple deployment'],
    lessonsLearned: ['Bot UX depends heavily on response timing'],
    tags: ['Python', 'Bot', 'AI'],
    futureImprovements: ['Better memory and context'],
  },
  {
    slug: 'pygame-chess',
    title: 'Pygame Chess',
    description: 'A chess game built with Python and Pygame featuring a playable board and classic rules.',
    longDescription: 'An interactive chess project focused on game logic, UI feedback, and a simple arcade-style experience.',
    technologies: ['Python', 'Pygame', 'HTML'],
    thumbnail: '/projects/chess.jpg',
    screenshots: [],
    githubUrl: 'https://github.com/Joseph-Wachira/pygameChess-main-master',
    liveUrl: '',
    status: 'Completed',
    completionDate: '2025',
    category: 'Game',
    featured: false,
    challenges: ['Chess rules implementation', 'Board interaction'],
    solutions: ['Turn-based game logic', 'Clear UI state management'],
    keyFeatures: ['Playable chess board', 'Piece movement', 'Simple UI'],
    lessonsLearned: ['Game logic grows quickly without structured state'],
    tags: ['Game', 'Python'],
    futureImprovements: ['AI opponent', 'Sound effects'],
  },
];